services:
  - type: web
    name: norman-digital-solutions
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: cambiar-esta-clave